"""
Django settings for Dev. Foundry Wallet.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os

import dotenv

# Load environment variables from .env file
dotenv.load_dotenv()

from .db_config import BASE_DIR, DATABASES
from .drf_auth_config import (AUTH_PASSWORD_VALIDATORS, REST_FRAMEWORK,
                              SIMPLE_JWT)
from .installed_apps import INSTALLED_APPS
from .middleware_config import MIDDLEWARE
from .openapi_config import SPECTACULAR_SETTINGS
from .templates_config import TEMPLATES

SECRET_KEY = os.getenv('SECRET_KEY', '')

BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')
TOKEN_TTL = os.getenv('TOKEN_TTL', 60)  # in minutes

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'


AUTH_USER_MODEL = 'users.User'


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
