# Generated by Django 5.1.7 on 2025-04-16 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_active_remove_user_is_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserKYCInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('VOTER_CARD', "Voter's Card"), ('NATIONAL_ID', 'National ID Card'), ('NIN', 'National Identification Number'), ('OTHER', 'Other')], max_length=50)),
                ('document_number', models.CharField(max_length=50)),
                ('document_image', models.CharField(max_length=255)),
                ('document_verified', models.BooleanField(default=False)),
                ('bvn', models.CharField(blank=True, max_length=11, null=True)),
                ('bvn_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_information', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User KYC Information',
                'verbose_name_plural': 'User KYC Information',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='users_userk_user_id_b7a81a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('UNCLE', 'Uncle'), ('AUNT', 'Aunt'), ('COUSIN', 'Cousin'), ('NEPHEW', 'Nephew'), ('NIECE', 'Niece'), ('SON', 'Son'), ('DAUGHTER', 'Daughter')], max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('state_LGA', models.IntegerField(blank=True, null=True, verbose_name='StateLGACode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Next of Kin',
                'verbose_name_plural': 'User Next of Kin',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='users_usern_user_id_2e9e6d_idx')],
            },
        ),
    ]
